import 'package:cached_network_image/cached_network_image.dart';
import 'package:cescpro/core/enum/app_enum.dart';
import 'package:cescpro/core/router/index.dart';
import 'package:cescpro/core/setting/app_loading.dart';
import 'package:cescpro/core/storage/app_event_bus.dart';
import 'package:cescpro/core/translations/en.dart';
import 'package:cescpro/generated/assets.dart';
import 'package:cescpro/http/api/site.dart';
import 'package:cescpro/http/bean/site_entity.dart';
import 'package:cescpro/page/station/index/widget/common_tag.dart';
import 'package:cescpro/page/station/index/widget/search_bar_widget.dart';
import 'package:cescpro/page/station/index/widget/status_tag.dart';
import 'package:easy_refresh/easy_refresh.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';

part 'logic.dart';
part 'view.dart';
