/*
// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'database/entity/home.dart';
import 'database/entity/user_profile.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5889303700164409998),
    name: 'Person',
    lastPropertyId: const obx_int.IdUid(6, 1220670412945539816),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4165556573441632459),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7978739855472237348),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3839201119137233389),
        name: 'avatar',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4136484801589392710),
        name: 'currencyCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1220670412945539816),
        name: 'uid',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8060802645335638365),
    name: 'Home',
    lastPropertyId: const obx_int.IdUid(16, 5562414059919676933),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8839229606867735307),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9142683552651726996),
        name: 'totalIncome',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1751625980054259248),
        name: 'todayIncome',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7766375291284166383),
        name: 'lastDayIncome',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 807875368477741575),
        name: 'deviceNum',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8826627317305839216),
        name: 'siteNum',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7125333897195291704),
        name: 'normalNum',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 3932149835475208445),
        name: 'faultNum',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 3539677074467370788),
        name: 'alarmNum',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 5562414059919676933),
        name: 'cutOffNum',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 8060802645335638365),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      353226606053880788,
      6442155453102333111,
      8302137427552492633,
      1347816219583240353,
      1127288714485779332,
      3355167394213769021,
      1142251929860121560,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Person: obx_int.EntityDefinition<Person>(
      model: _entities[0],
      toOneRelations: (Person object) => [],
      toManyRelations: (Person object) => {},
      getId: (Person object) => object.id,
      setId: (Person object, int id) {
        object.id = id;
      },
      objectToFB: (Person object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final avatarOffset = fbb.writeString(object.avatar);
        final currencyCodeOffset = fbb.writeString(object.currencyCode);
        final uidOffset = fbb.writeString(object.uid);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, avatarOffset);
        fbb.addOffset(4, currencyCodeOffset);
        fbb.addOffset(5, uidOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final avatarParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final currencyCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = Person(
          id: idParam,
          name: nameParam,
          avatar: avatarParam,
          currencyCode: currencyCodeParam,
          uid: uidParam,
        );

        return object;
      },
    ),
    Home: obx_int.EntityDefinition<Home>(
      model: _entities[1],
      toOneRelations: (Home object) => [],
      toManyRelations: (Home object) => {},
      getId: (Home object) => object.id,
      setId: (Home object, int id) {
        object.id = id;
      },
      objectToFB: (Home object, fb.Builder fbb) {
        final totalIncomeOffset = fbb.writeString(object.totalIncome);
        final todayIncomeOffset = fbb.writeString(object.todayIncome);
        final lastDayIncomeOffset = fbb.writeString(object.lastDayIncome);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, totalIncomeOffset);
        fbb.addOffset(2, todayIncomeOffset);
        fbb.addOffset(3, lastDayIncomeOffset);
        fbb.addInt64(4, object.deviceNum);
        fbb.addInt64(5, object.siteNum);
        fbb.addInt64(12, object.normalNum);
        fbb.addInt64(13, object.faultNum);
        fbb.addInt64(14, object.alarmNum);
        fbb.addInt64(15, object.cutOffNum);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final totalIncomeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final todayIncomeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final lastDayIncomeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final deviceNumParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final siteNumParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final normalNumParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final faultNumParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        final alarmNumParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        final cutOffNumParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          34,
          0,
        );
        final object = Home(
          id: idParam,
          totalIncome: totalIncomeParam,
          todayIncome: todayIncomeParam,
          lastDayIncome: lastDayIncomeParam,
          deviceNum: deviceNumParam,
          siteNum: siteNumParam,
          normalNum: normalNumParam,
          faultNum: faultNumParam,
          alarmNum: alarmNumParam,
          cutOffNum: cutOffNumParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Person] entity fields to define ObjectBox queries.
class Person_ {
  /// See [Person.id].
  static final id = obx.QueryIntegerProperty<Person>(
    _entities[0].properties[0],
  );

  /// See [Person.name].
  static final name = obx.QueryStringProperty<Person>(
    _entities[0].properties[1],
  );

  /// See [Person.avatar].
  static final avatar = obx.QueryStringProperty<Person>(
    _entities[0].properties[2],
  );

  /// See [Person.currencyCode].
  static final currencyCode = obx.QueryStringProperty<Person>(
    _entities[0].properties[3],
  );

  /// See [Person.uid].
  static final uid = obx.QueryStringProperty<Person>(
    _entities[0].properties[4],
  );
}

/// [Home] entity fields to define ObjectBox queries.
class Home_ {
  /// See [Home.id].
  static final id = obx.QueryIntegerProperty<Home>(_entities[1].properties[0]);

  /// See [Home.totalIncome].
  static final totalIncome = obx.QueryStringProperty<Home>(
    _entities[1].properties[1],
  );

  /// See [Home.todayIncome].
  static final todayIncome = obx.QueryStringProperty<Home>(
    _entities[1].properties[2],
  );

  /// See [Home.lastDayIncome].
  static final lastDayIncome = obx.QueryStringProperty<Home>(
    _entities[1].properties[3],
  );

  /// See [Home.deviceNum].
  static final deviceNum = obx.QueryIntegerProperty<Home>(
    _entities[1].properties[4],
  );

  /// See [Home.siteNum].
  static final siteNum = obx.QueryIntegerProperty<Home>(
    _entities[1].properties[5],
  );

  /// See [Home.normalNum].
  static final normalNum = obx.QueryIntegerProperty<Home>(
    _entities[1].properties[6],
  );

  /// See [Home.faultNum].
  static final faultNum = obx.QueryIntegerProperty<Home>(
    _entities[1].properties[7],
  );

  /// See [Home.alarmNum].
  static final alarmNum = obx.QueryIntegerProperty<Home>(
    _entities[1].properties[8],
  );

  /// See [Home.cutOffNum].
  static final cutOffNum = obx.QueryIntegerProperty<Home>(
    _entities[1].properties[9],
  );
}
*/
